# Generated by Django 4.1.1 on 2022-09-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rating', models.FloatField(default=0)),
                ('alternate_titles', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('author', models.CharField(max_length=50, null=True)),
                ('artist', models.CharField(max_length=50, null=True)),
                ('created_on', models.DateField(null=True)),
                ('posted_on', models.DateTimeField(null=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('keywords', models.TextField(null=True)),
            ],
        ),
    ]
